/**
 * Row types for the seven tables in supabase/migrations/.
 *
 * Hand-written rather than generated, because generation needs a live
 * connection at build time and CI has no database credentials. The migration
 * files are the source of truth (hard rule 10) — when one changes, this
 * changes in the same commit.
 *
 * `Insert` shapes omit anything the database fills in: the uuid default, the
 * timestamps, and any column with a server-side default.
 */

/** `lead_source` — 8 values, matching 0001_initial_schema.sql. */
export const leadSources = [
  "contact_form",
  "audit_request",
  "newsletter",
  "chat_widget",
  "booking",
  "crawlmouse_referral",
  "outreach",
  "other",
  /** The form embedded at the foot of each service page. See 0004. */
  "service_page",
] as const;
export type LeadSource = (typeof leadSources)[number];

/** `lead_status` — 7 values. Set by hand after a lead lands; never by the app. */
export const leadStatuses = [
  "new",
  "contacted",
  "qualified",
  "proposal",
  "won",
  "lost",
  "disqualified",
] as const;
export type LeadStatus = (typeof leadStatuses)[number];

/**
 * `service_interest` — 8 values.
 *
 * `local_seo` is retained deliberately: Postgres cannot drop an enum value
 * without recreating the type, and existing rows may reference it. New leads
 * use `ai_search_visibility` instead. See 0002_service_enum.sql.
 */
export const serviceInterests = [
  "ai_search_visibility",
  "local_seo",
  "web_development",
  "ai_automation",
  "unsure",
  "other",
  "ai_consultancy",
  "software_development",
] as const;
export type ServiceInterest = (typeof serviceInterests)[number];

export type LeadInsert = {
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  website?: string | null;
  employee_count?: string | null;
  vertical?: string | null;
  city?: string | null;
  currently_marketing?: boolean | null;
  source: LeadSource;
  service_interest?: ServiceInterest | null;
  message?: string | null;
  landing_page?: string | null;
  referrer?: string | null;
  utm_source?: string | null;
  utm_medium?: string | null;
  utm_campaign?: string | null;
  locale?: string | null;
};

export type LeadRow = LeadInsert & {
  id: string;
  created_at: string;
  updated_at: string;
  status: LeadStatus;
  first_contacted_at: string | null;
  notes: string | null;
};

export type LeadEventInsert = {
  lead_id: string;
  event_type: string;
  detail?: Record<string, unknown>;
};

export type NewsletterSubscriberInsert = {
  email: string;
  locale?: string | null;
  source_page?: string | null;
};

export type ChatConversationInsert = {
  /**
   * Generated by the browser. anon has no SELECT privilege, so
   * `INSERT ... RETURNING` is unavailable and the client cannot read an id
   * back — it has to supply one.
   */
  id: string;
  session_id: string;
  lead_id?: string | null;
  landing_page?: string | null;
  locale?: string | null;
  user_agent?: string | null;
};

export type ChatMessageInsert = {
  /** Client-generated, for the same reason as `ChatConversationInsert.id`. */
  id: string;
  conversation_id: string;
  role: "user" | "assistant";
  /** The table enforces `char_length(content) <= 8000`. */
  content: string;
};

export type NotificationLogInsert = {
  lead_id?: string | null;
  channel: string;
  status: "sent" | "failed";
  error?: string | null;
};
